---
name: Build - Ubuntu

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - otxserv6

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        buildtype: [linux-release]
        include:
          - os: ubuntu-20.04
            triplet: x64-linux
          - os: ubuntu-22.04
            triplet: x64-linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@otxserv6

      - name: Install Linux Dependencies
        run: >
          sudo apt-get update && sudo apt-get install ccache linux-headers-$(uname -r)

      - name: Switch to gcc-11
        run: |
          sudo apt install gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
          sudo update-alternatives --set gcc /usr/bin/gcc-11

      - name: CCache
        uses: hendrikmuhs/ccache-action@otxserv6
        with:
          max-size: "1G"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Restore artifacts and install vcpkg
        uses: lukka/run-vcpkg@otxserv6
        with:
          vcpkgGitURL: "https://github.com/otxserver/vcpkg.git"
          vcpkgGitCommitId: 8974d642d47efd578e0da3223b4101c5d59aebcf

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@otxserv6

      - name: Run CMake
        uses: lukka/run-cmake@otxserv6
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@otxserv6
        with:
          name: otx-${{ matrix.os }}-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
