---
name: Build - Windows

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - otxserv6

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  MAKEFLAGS: '-j 2'

jobs:
  job:
    name: ${{ matrix.os }}-${{ matrix.buildtype }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022]
        buildtype: [windows-release]
        include:
          - os: windows-2022
            triplet: x64-windows
            packages: >
              sccache

    steps:
      - name: Checkout repository
        uses: actions/checkout@otxserv6

      - name: CCache
        uses: hendrikmuhs/ccache-action@otxserv6
        with:
          max-size: "1G"
          variant: "sccache"
          key: ccache-${{ matrix.os }}-${{ matrix.buildtype }}
          restore-keys: |
            ccache-${{ matrix.os }}

      - name: Remove Windows pre-installed MySQL
        if: contains( matrix.os, 'windows')
        run: rm -r -fo C:/mysql*

      - name: Restore artifacts and install vcpkg
        uses: lukka/run-vcpkg@otxserv6
        with:
          vcpkgGitURL: "https://github.com/otxserver/vcpkg.git"
          vcpkgGitCommitId: 8974d642d47efd578e0da3223b4101c5d59aebcf

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@otxserv6

      - name: Run CMake
        uses: lukka/run-cmake@otxserv6
        with:
          configurePreset: ${{ matrix.buildtype }}
          buildPreset: ${{ matrix.buildtype }}

      - name: Create and Upload Artifact
        uses: actions/upload-artifact@otxserv6
        with:
          name: otx-${{ matrix.buildtype }}-${{ github.sha }}
          path: |
            ${{ github.workspace }}/build/${{ matrix.buildtype }}/bin/
